dist: bionic
language: php
php:
  - '7.3'
  - '7.4'
before_install:
  - sudo apt-get -y install poppler-utils
install:
  - composer install
script:
  - ./vendor/bin/phpunit  --bootstrap ./vendor/autoload.php ./test/ --testdox
